env:
  browser: true
  es6: true

parser: babel-eslint

plugins:
  - prettier

extends:
  - eslint:recommended
  - plugin:prettier/recommended

globals:
  chrome: true

rules:
  prettier/prettier:
    - error
    - printWidth: 120
      singleQuote: true
      trailingComma: all
